{
 "title": "ComfoConnect",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Supply flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"120\"}"
    }
   ]
  },
  {
   "title": "Outdoor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"220\"} / 10"
    }
   ]
  },
  {
   "title": "Outdoor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"292\"}"
    }
   ]
  },
  {
   "title": "Preheater",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{description=\"Preheater Power Consumption: Current Ventilation\"}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"65\"}"
    }
   ]
  },
  {
   "title": "Exhaust",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"275\"} /10"
    }
   ]
  },
  {
   "title": "Exhaust",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"291\"}"
    }
   ]
  },
  {
   "title": "Exhaust flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"119\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 2 },
   "options": {
    "content": "<div style=\"font-size: 25pt; width:100%; text-align: center;\">&darr;</div>"
   },
   "content": "<div style=\"font-size: 25pt; width:100%; text-align: center;\">&darr;</div>"
  },
  {
   "title": "Frost protection",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{description=\"Unknown Frost Protection Unbalance\"}",
     "legendFormat": "Unbalance"
    }
   ]
  },
  {
   "title": "Bypass",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{description=\"Bypass state\"}",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "options": {
    "content": "<div style=\"font-size: 25pt; width:100%; text-align: center;\">&uarr;</div>"
   },
   "content": "<div style=\"font-size: 25pt; width:100%; text-align: center;\">&darr;</div>"
  },
  {
   "title": "Supply flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"122\"}"
    }
   ]
  },
  {
   "title": "Exhaust flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"121\"}"
    }
   ]
  },
  {
   "title": "Supply",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"221\"} / 10"
    }
   ]
  },
  {
   "title": "Supply",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"294\"}"
    }
   ]
  },
  {
   "title": "Extract",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"274\"} / 10"
    }
   ]
  },
  {
   "title": "Extract",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{ID=\"290\"}"
    }
   ]
  },
  {
   "title": "Temperature difference extract and supply",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(comfoconnect_pdo_value{ID=\"221\"}) - sum(comfoconnect_pdo_value{ID=\"274\"})) / 10"
    }
   ]
  },
  {
   "title": "temp+hum",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{description=~\"Temper.*\"} /10 < 100",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "comfoconnect_pdo_value{description=~\"Humidity.*\"}  < 100",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "comfoconnect_pdo_value{description=~\".*RMOT.*\"} /10 < 100",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "power",
   "type": "graph",
   "description": "fix total format",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{description=~\".*onsumption.*\"}",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "comfoconnect_pdo_value{description=~\".*voided.*\"}",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "bypass",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{description=\"Bypass state\"}",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "fans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "comfoconnect_pdo_value{description=~\"Fan.*speed\"}",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "comfoconnect_pdo_value{description=~\"Fan.*flow\"}",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "comfoconnect_pdo_value{description=~\"Fan.*duty\"}",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "all",
   "type": "graph",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(comfoconnect_proxy_client_message_fromGateway_total[20s])"
    },
    {
     "expr": "rate(comfoconnect_proxy_client_message_toGateway_total[20s])"
    },
    {
     "expr": "comfoconnect_proxy_client_connected_bool"
    },
    {
     "expr": "comfoconnect_proxy_listener_connections"
    },
    {
     "expr": "rate(comfoconnect_proxy_listener_message_received_total[20s])"
    },
    {
     "expr": "rate(comfoconnect_proxy_listener_message_receiver_total[20s])"
    },
    {
     "expr": "rate(comfoconnect_proxy_listener_message_sent_total[20s])"
    },
    {
     "expr": "comfoconnect_proxy_proxy_fromGateway_queue_length"
    },
    { "expr": "comfoconnect_pdo_value", "legendFormat": "{{ID}}: {{description}}" }
   ]
  }
 ]
}